import ClientSessionProvider from "@/components/ClientSessionProvider";
import { authOptions } from "@/constants/auth";
import type { Metadata } from "next";
import { getServerSession } from "next-auth";
import "./globals.scss";
import LocaleContext from "@/context/LocaleContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);
  return (
    <html lang='en' style={{ fontSize: "0.9rem" }}>
      <head></head>
      <body>
        <LocaleContext>
          <ClientSessionProvider session={session}>{children}</ClientSessionProvider>
        </LocaleContext>
      </body>
    </html>
  );
}
